#!/usr/bin/env python3
"""Generate the embedded hardware-config header used by the wiring test tool.

Reads a hardware config JSON file from the path in $ASP_WIRING_CONFIG and
writes a C++ header containing the file contents as a raw string literal
plus the basename, so the wiring firmware can parse it at boot without
needing a runtime LittleFS loader.

Used as a PlatformIO ``extra_scripts`` pre-build hook for the
``nodemcu-32s-wiring-test`` env. The Makefile target ``test-esp32-wiring``
sets ``ASP_WIRING_CONFIG`` from the user's ``CONFIG=`` argument before
invoking ``pio run``.

Standalone invocation (for the host-side test):

    python scripts/generate_wiring_config_header.py \\
        --config data/config.json \\
        --output /tmp/wiring_config_embedded.h
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path

HEADER_TEMPLATE = """\
// AUTO-GENERATED by scripts/generate_wiring_config_header.py.
// Do not edit by hand. Regenerated on every wiring-test build from
// the file named by ASP_WIRING_CONFIG (set by the Make target).

#pragma once

namespace wiring_test {{

inline constexpr const char* CONFIG_FILENAME = "{filename}";

inline constexpr const char* CONFIG_JSON = R"WIRING_JSON({payload}
)WIRING_JSON";

}}  // namespace wiring_test
"""


def generate(config_path: Path, output_path: Path) -> None:
    if not config_path.is_file():
        raise SystemExit(
            f"generate_wiring_config_header: config not readable: {config_path}"
        )

    raw = config_path.read_text(encoding="utf-8")

    try:
        json.loads(raw)
    except json.JSONDecodeError as exc:
        raise SystemExit(
            f"generate_wiring_config_header: {config_path} is not valid JSON: {exc}"
        )

    if "WIRING_JSON" in raw:
        raise SystemExit(
            "generate_wiring_config_header: config contains the raw-string "
            "delimiter 'WIRING_JSON'; rename the conflicting key and retry"
        )

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        HEADER_TEMPLATE.format(filename=config_path.name, payload=raw.rstrip("\n")),
        encoding="utf-8",
    )


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(
        description="Generate wiring_config_embedded.h from a hardware config JSON."
    )
    parser.add_argument(
        "--config",
        type=Path,
        default=None,
        help="Path to hardware config JSON. Defaults to $ASP_WIRING_CONFIG.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        required=True,
        help="Path to write the generated header.",
    )
    args = parser.parse_args(argv)

    config_path = args.config
    if config_path is None:
        env_path = os.environ.get("ASP_WIRING_CONFIG", "").strip()
        if not env_path:
            raise SystemExit(
                "generate_wiring_config_header: --config not given and "
                "ASP_WIRING_CONFIG is empty. Run via 'make test-esp32-wiring "
                "CONFIG=<path>' or pass --config explicitly."
            )
        config_path = Path(env_path)

    if not config_path.is_absolute():
        config_path = (Path.cwd() / config_path).resolve()

    generate(config_path, args.output)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))


# ---------------------------------------------------------------------------
# PlatformIO pre-build hook entry-point.
#
# When PlatformIO sources this file via ``extra_scripts = pre:scripts/...``
# it injects the SCons env into module globals as ``Import("env")``. We
# detect that and run the same generator inline, writing the header into
# the env's build dir so it's both gitignored and added to CPPPATH.
# ---------------------------------------------------------------------------
try:
    Import  # type: ignore[name-defined]  # noqa: F821
    _is_pio_extra_script = True
except NameError:
    _is_pio_extra_script = False

if _is_pio_extra_script:
    Import("env")  # type: ignore  # noqa: F821
    env = globals()["env"]  # type: ignore[assignment]

    _config_env = os.environ.get("ASP_WIRING_CONFIG", "").strip()
    if not _config_env:
        sys.stderr.write(
            "\n[wiring-test] ASP_WIRING_CONFIG is unset.\n"
            "Run via:  make test-esp32-wiring CONFIG=<path-to-hardware-config.json>\n\n"
        )
        env.Exit(1)  # type: ignore[attr-defined]

    _config_path = Path(_config_env)
    if not _config_path.is_absolute():
        _config_path = (Path(env["PROJECT_DIR"]) / _config_path).resolve()  # type: ignore[index]

    if not _config_path.is_file():
        sys.stderr.write(
            f"\n[wiring-test] config not readable: {_config_path}\n"
            "Pass CONFIG=<path-to-existing-hardware-config.json>.\n\n"
        )
        env.Exit(1)  # type: ignore[attr-defined]

    _build_dir = Path(env.subst("$BUILD_DIR"))  # type: ignore[attr-defined]
    _output = _build_dir / "wiring_config_embedded.h"

    generate(_config_path, _output)

    env.Append(CPPPATH=[str(_build_dir)])  # type: ignore[attr-defined]
    print(f"[wiring-test] embedded {_config_path.name} -> {_output}")
